spring:
  application:
    name: 09-security
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/login?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  session:
    store-type: redis
    timeout: 180
server:
  port: 8001
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
